# Site wide configuration

title:            Rabid Canary
locale:           en_EN
url:


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true


# Site owner
owner:
  name: Matt McCabe
  avatar: profile.png
  bio: "A Full-Stack Web Developer currently enjoying Aurelia and tuning SQL queries."
  email:
  disqus-shortname:
  twitter: mttmccb
  google:
    analytics: <meta name="google-site-verification" content="UxFF4CTfk-hsriBiUa1KphhUI_SPs1-Gmau-w3BFW5k" />
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: mttmccb
  stackoverflow: 2193900/matt-mccabe

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
